# ---------------------------------------------------------------
# Ansible Inventory
#
# ** YOUR TASK (For production aka): Replace the ansible_host value below with the
# IP output from: terraform output web_server_ip
#
# For LocalStack/Docker lab: use 127.0.0.1 with port 2222
# note for you btw -> For real AWS: paste the actual public IP from Terraform output
# ---------------------------------------------------------------

[webservers]
web1 ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root ansible_ssh_pass=labpassword

[webservers:vars]
environment=dev

# ---------------------------------------------------------------
# a little challenge for you : Replace static inventory with dynamic
# inventory that auto-reads from Terraform state:  and fork it to my repo
#   ansible-inventory --list (with terraform_inventory plugin)
# ---------------------------------------------------------------
